/** The daily puzzle bank. One puzzle a day, in this order, starting on LAUNCH_DAY. Add new ones at the end. */
export type Puzzle = {
  title: string;
  topic: "Probability" | "Expected value" | "Counting" | "Logic" | "Markets" | "Estimation";
  level: 1 | 2 | 3;
  prompt: string;
  /** The exact answer. Fractions typed by students are converted to decimals before checking. */
  answer: number;
  /** How the answer is written in the solution, e.g. "1/6". */
  shown: string;
  /** True when the answer itself is a percent, so "25" and "25%" both mean 25. */
  percent?: boolean;
  hint: string;
  why: string;
};

export const LAUNCH_DAY = "2026-10-09";

export const PUZZLES: Puzzle[] = [
  { title: "Lucky seven", topic: "Probability", level: 1,
    prompt: "You roll two fair dice. What is the probability that they add up to 7?",
    answer: 1 / 6, shown: "1/6",
    hint: "There are 36 equally likely pairs. Count the ones that make 7.",
    why: "Six pairs make 7: (1,6), (2,5), (3,4), (4,3), (5,2), (6,1). That is 6 out of 36, or 1/6. No other total has more ways." },
  { title: "Bat and ball", topic: "Logic", level: 1,
    prompt: "A bat and a ball cost $1.10 together. The bat costs $1.00 more than the ball. How many cents does the ball cost?",
    answer: 5, shown: "5 cents",
    hint: "If the ball cost 10 cents, the bat would cost $1.10, and the total would be $1.20.",
    why: "Call the ball x. Then x + (x + 1.00) = 1.10, so 2x = 0.10 and x = 0.05. The quick answer of 10 cents is the trap that interviewers love." },
  { title: "Wait for a six", topic: "Expected value", level: 1,
    prompt: "You roll a fair die until you get a 6. On average, how many rolls does it take?",
    answer: 6, shown: "6",
    hint: "Each roll succeeds with probability 1/6. If something succeeds with probability p, you wait 1/p tries on average.",
    why: "This is a geometric distribution with p = 1/6, and its average is 1/p = 6 rolls." },
  { title: "Up 50, down 50", topic: "Markets", level: 1,
    prompt: "A stock rises 50% on Monday and falls 50% on Tuesday. What is its total percent change over the two days?",
    answer: -25, shown: "-25%", percent: true,
    hint: "Start with $100 and follow it through both days.",
    why: "$100 becomes $150, then half of $150 is $75. That is a 25% loss. Losses hurt more than equal-sized gains help, which is why volatility drags on returns." },
  { title: "Let's make a deal", topic: "Probability", level: 2,
    prompt: "A prize is behind one of 3 doors. You pick door 1. The host, who knows where the prize is, opens another door with nothing behind it and offers you a switch. If you switch, what is your probability of winning?",
    answer: 2 / 3, shown: "2/3",
    hint: "Your first pick is right 1/3 of the time. When it is wrong, where must the prize be after the host opens a door?",
    why: "You started right 1/3 of the time, so staying wins 1/3. The other 2/3 of the time the prize is behind one of the other doors, and the host just showed you which one. Switching wins 2/3." },
  { title: "The reroll", topic: "Expected value", level: 2,
    prompt: "You roll a die and win that many dollars. After seeing the first roll you may reroll once, but then you must keep the second roll. Playing as well as possible, what is your expected winnings in dollars?",
    answer: 4.25, shown: "$4.25",
    hint: "A reroll is worth 3.5 on average. Which first rolls are worth keeping?",
    why: "Keep 4, 5 or 6, since each beats 3.5. Half the time you keep, averaging 5. Half the time you reroll and get 3.5. So 0.5 × 5 + 0.5 × 3.5 = 4.25. Comparing a sure thing with the value of waiting is a core trading skill." },
  { title: "Same birthday", topic: "Probability", level: 2,
    prompt: "What is the smallest number of people you need in a room for there to be a better than 50% chance that two of them share a birthday? (Ignore leap years.)",
    answer: 23, shown: "23",
    hint: "It is much smaller than 183. Think about how many pairs of people there are.",
    why: "With 23 people the chance that all birthdays differ drops to about 49.3%, so a shared birthday is slightly more likely than not. 23 people make 253 pairs, which is why it happens so soon." },
  { title: "Two heads in a row", topic: "Expected value", level: 3,
    prompt: "You flip a fair coin until you get two heads in a row. On average, how many flips does it take?",
    answer: 6, shown: "6",
    hint: "Let E be the expected flips from the start. Write an equation for what happens after the first flip, and after a head.",
    why: "From the start, E = 1 + ½·(after a head) + ½·E. After a head, you need 1 + ½·0 + ½·E more. Solving gives E = 6." },
  { title: "Two aces", topic: "Probability", level: 2,
    prompt: "You draw 2 cards from a shuffled 52-card deck. What is the probability that both are aces?",
    answer: 1 / 221, shown: "1/221",
    hint: "Multiply the chance the first is an ace by the chance the second is an ace given the first was.",
    why: "4/52 × 3/51 = 12/2652 = 1/221, a little under half a percent." },
  { title: "Handshakes", topic: "Counting", level: 1,
    prompt: "Ten people meet and everyone shakes hands with everyone else exactly once. How many handshakes happen?",
    answer: 45, shown: "45",
    hint: "Each handshake is a pair of people. How many pairs can you choose from 10?",
    why: "10 choose 2 = 10 × 9 / 2 = 45. Each person shakes 9 hands, but that counts every handshake twice." },
  { title: "Rule of 72", topic: "Markets", level: 1,
    prompt: "Using the rule of 72, about how many years does it take money growing at 8% a year to double?",
    answer: 9, shown: "9 years",
    hint: "Divide 72 by the growth rate in percent.",
    why: "72 / 8 = 9. The exact answer is 9.006 years, so the shortcut is very close." },
  { title: "Size the bet", topic: "Markets", level: 3,
    prompt: "A bet pays even money and you win it 60% of the time. Using the Kelly criterion, what percent of your bankroll should you bet?",
    answer: 20, shown: "20%", percent: true,
    hint: "For an even-money bet, the Kelly fraction is p − q, where q = 1 − p.",
    why: "0.60 − 0.40 = 0.20, so bet 20%. Betting more grows your money more slowly on average and risks ruin, even though every bet has a positive expected value." },
  { title: "Three ants", topic: "Probability", level: 2,
    prompt: "Three ants sit at the corners of a triangle. Each picks a random direction along the edges and walks at the same speed. What is the probability that no two ants run into each other?",
    answer: 1 / 4, shown: "1/4",
    hint: "There are 8 equally likely ways to pick directions. Which ones avoid every collision?",
    why: "Only all-clockwise or all-counterclockwise avoids a crash. That is 2 of 8, or 1/4." },
  { title: "Lily pads", topic: "Logic", level: 1,
    prompt: "A patch of lily pads doubles in size every day. It covers the whole pond on day 48. On what day did it cover half the pond?",
    answer: 47, shown: "Day 47",
    hint: "Work backward one day.",
    why: "If it doubles each day and is full on day 48, it was half full one day earlier. Exponential growth looks small right up until the end." },
  { title: "Collect them all", topic: "Expected value", level: 3,
    prompt: "You roll a fair die until every face from 1 to 6 has appeared at least once. On average, how many rolls does it take? (Give one decimal place.)",
    answer: 14.7, shown: "14.7",
    hint: "After you have seen k faces, a new face shows up with probability (6 − k)/6. Add up the waits for each new face.",
    why: "6/6 + 6/5 + 6/4 + 6/3 + 6/2 + 6/1 = 6 × (1 + 1/2 + 1/3 + 1/4 + 1/5 + 1/6) = 14.7. This is the coupon collector problem." },
  { title: "Two kids", topic: "Probability", level: 2,
    prompt: "A family has two children, and you are told at least one of them is a boy. What is the probability that both are boys?",
    answer: 1 / 3, shown: "1/3",
    hint: "List the equally likely families: BB, BG, GB, GG. Which ones fit what you were told?",
    why: "GG is ruled out, leaving BB, BG and GB. Only one of those three is two boys, so 1/3, not 1/2." },
  { title: "Broken stick", topic: "Probability", level: 3,
    prompt: "You break a stick at two points chosen at random along its length. What is the probability that the three pieces can form a triangle?",
    answer: 1 / 4, shown: "1/4",
    hint: "The pieces form a triangle exactly when no piece is longer than half the stick.",
    why: "Plot the two break points in a unit square. The region where every piece is under ½ is a quarter of the square, so the answer is 1/4." },
  { title: "Call option payoff", topic: "Markets", level: 1,
    prompt: "You pay $5 for a call option with a strike price of $100. At expiration the stock is at $112. What is your profit per share in dollars?",
    answer: 7, shown: "$7",
    hint: "A call lets you buy at the strike. What is that worth, and what did it cost you?",
    why: "The option is worth 112 − 100 = $12. Subtract the $5 you paid and you made $7 per share." },
  { title: "Breakeven", topic: "Markets", level: 1,
    prompt: "You buy a call option with a $100 strike for $5. Ignoring fees, at what stock price at expiration do you exactly break even?",
    answer: 105, shown: "$105",
    hint: "The option has to be worth exactly what you paid.",
    why: "At $105 the call is worth $5, the same as its cost. Above $105 you profit. Below it you lose, up to the full $5." },
  { title: "Locker hallway", topic: "Logic", level: 2,
    prompt: "100 closed lockers stand in a hall. Student 1 opens every locker. Student 2 toggles every 2nd locker, student 3 every 3rd, and so on up to student 100. How many lockers are open at the end?",
    answer: 10, shown: "10",
    hint: "A locker is toggled once for each of its divisors. Which numbers have an odd number of divisors?",
    why: "Divisors come in pairs, except for perfect squares, where one divisor pairs with itself. Only the squares 1, 4, 9, …, 100 end open, and there are 10 of them." },
  { title: "The heavy coin", topic: "Logic", level: 2,
    prompt: "You have 9 coins and one of them is slightly heavier. Using a balance scale, what is the fewest number of weighings that always finds the heavy coin?",
    answer: 2, shown: "2",
    hint: "Each weighing has three outcomes: left heavy, right heavy, or balanced.",
    why: "Split into three groups of 3 and weigh two of them. That tells you which group has the heavy coin. Then weigh two coins from that group. Each weighing cuts the options by 3, and 3 × 3 = 9." },
  { title: "Poisoned bottle", topic: "Logic", level: 3,
    prompt: "One of 1,000 bottles is poisoned. Testers who drink from a poisoned bottle show a reaction the next day. You have one day. What is the fewest testers you need to find the bottle for sure?",
    answer: 10, shown: "10",
    hint: "Write each bottle's number in binary.",
    why: "Number the bottles in binary. Tester k drinks from every bottle whose k-th bit is 1. The pattern of reactions spells out the poisoned bottle's number. 2^10 = 1,024 ≥ 1,000, so 10 testers are enough." },
  { title: "Worth taking?", topic: "Expected value", level: 1,
    prompt: "A bet wins $10 with probability 30% and loses $4 otherwise. What is its expected value in dollars?",
    answer: 0.2, shown: "$0.20",
    hint: "Multiply each outcome by its probability and add.",
    why: "0.3 × 10 − 0.7 × 4 = 3 − 2.8 = $0.20. Small, but positive. Repeat it thousands of times and that edge is how trading firms make money." },
  { title: "Even product", topic: "Probability", level: 1,
    prompt: "You roll two dice and multiply the numbers. What is the probability that the product is even?",
    answer: 3 / 4, shown: "3/4",
    hint: "It is easier to find the chance that the product is odd.",
    why: "The product is odd only when both dice are odd: ½ × ½ = ¼. So it is even with probability 1 − ¼ = 3/4." },
  { title: "Round trip", topic: "Logic", level: 2,
    prompt: "You drive to a town at 60 mph and drive back the same route at 30 mph. What is your average speed for the whole trip in mph?",
    answer: 40, shown: "40 mph",
    hint: "Pick a distance, like 60 miles each way, and find the total time.",
    why: "60 miles there takes 1 hour, and 60 miles back takes 2 hours. That is 120 miles in 3 hours, or 40 mph. You spend more time at the slow speed, so the average is not 45." },
  { title: "Darts at a square", topic: "Estimation", level: 2,
    prompt: "A dart lands at a random point in a square. A circle fits exactly inside the square. What is the probability the dart lands inside the circle? (Give 3 decimal places.)",
    answer: Math.PI / 4, shown: "π/4 ≈ 0.785",
    hint: "Compare the circle's area to the square's area. Use a radius of 1.",
    why: "The circle has area π and the square has area 4, so the chance is π/4 ≈ 0.785. Throw enough darts and you can estimate π. That trick is called Monte Carlo simulation." },
  { title: "Snail in a well", topic: "Logic", level: 1,
    prompt: "A snail is at the bottom of a 10-foot well. Each day it climbs 3 feet, and each night it slips back 2 feet. On which day does it reach the top?",
    answer: 8, shown: "Day 8",
    hint: "On the last day it climbs out and does not slip back.",
    why: "After 7 days and nights it is at 7 feet. On day 8 it climbs 3 feet to reach 10 and is out. The answer is not 10." },
  { title: "Compound interest", topic: "Markets", level: 1,
    prompt: "You invest $100 at 10% per year, compounded once a year. How many dollars do you have after 2 years?",
    answer: 121, shown: "$121",
    hint: "The second year earns interest on the first year's interest too.",
    why: "100 × 1.1 = 110, then 110 × 1.1 = 121. The extra $1 over simple interest is interest on interest." },
  { title: "Scramble TRADER", topic: "Counting", level: 2,
    prompt: "How many different ways can you arrange the letters of the word TRADER?",
    answer: 360, shown: "360",
    hint: "There are 6 letters, but the R appears twice.",
    why: "6! = 720 orderings, but swapping the two Rs gives the same word, so divide by 2: 360." },
  { title: "Back where it started", topic: "Expected value", level: 3,
    prompt: "10 students hand in their phones, which are given back at random. On average, how many students get their own phone back?",
    answer: 1, shown: "1",
    hint: "Each student gets their own phone with probability 1/10. Expected values add up even when events depend on each other.",
    why: "Each of the 10 students has a 1/10 chance, and by linearity of expectation the average total is 10 × 1/10 = 1. Amazingly, it is 1 for any number of students." },
  { title: "Spread of a die", topic: "Probability", level: 3,
    prompt: "What is the variance of a single roll of a fair six-sided die? (Give 2 decimal places.)",
    answer: 35 / 12, shown: "35/12 ≈ 2.92",
    hint: "Variance = average of the squares − square of the average. The average of 1² through 6² is 91/6.",
    why: "91/6 − 3.5² = 15.17 − 12.25 = 35/12 ≈ 2.92. Variance measures how spread out outcomes are, and it is the basis of risk in finance." },
  { title: "Gambler's ruin", topic: "Probability", level: 3,
    prompt: "You have $3. You bet $1 on fair coin flips until you have $10 or go broke. What is the probability that you reach $10?",
    answer: 0.3, shown: "0.3",
    hint: "In a fair game your expected money never changes, so the average at the end must still be $3.",
    why: "If p is the chance of ending at $10, the expected ending amount is 10p, and in a fair game that equals your starting $3. So p = 0.3." },
  { title: "Price a square", topic: "Expected value", level: 2,
    prompt: "A game pays you the square of a die roll in dollars (a 4 pays $16). What is the fair price to play, in dollars? (Give 2 decimal places.)",
    answer: 91 / 6, shown: "91/6 ≈ $15.17",
    hint: "Average 1, 4, 9, 16, 25 and 36.",
    why: "(1 + 4 + 9 + 16 + 25 + 36) / 6 = 91/6 ≈ $15.17. Notice it is more than 3.5² = 12.25. The average of squares beats the square of the average." },
  { title: "A die-roll option", topic: "Markets", level: 2,
    prompt: "An option pays the amount by which a die roll beats 3, and nothing otherwise. A 5 pays $2 and a 2 pays $0. What is its fair price in dollars?",
    answer: 1, shown: "$1",
    hint: "Only rolls of 4, 5 and 6 pay anything.",
    why: "The payoffs are 0, 0, 0, 1, 2, 3, which average to 6/6 = $1. This is a call option with strike 3, priced by expected value." },
  { title: "Hunting an ace", topic: "Expected value", level: 3,
    prompt: "You flip cards one at a time from a shuffled 52-card deck. On average, how many cards do you flip to reach the first ace, counting the ace? (Give 1 decimal place.)",
    answer: 10.6, shown: "10.6",
    hint: "The 4 aces split the 48 other cards into 5 gaps that are the same size on average.",
    why: "Each of the 5 gaps holds 48/5 = 9.6 non-aces on average. Flip those and then the ace: 9.6 + 1 = 10.6." },
  { title: "Third time's the charm", topic: "Probability", level: 1,
    prompt: "You flip a fair coin. What is the probability that the first head comes on exactly the third flip?",
    answer: 1 / 8, shown: "1/8",
    hint: "That means tails, tails, then heads.",
    why: "½ × ½ × ½ = 1/8." },
  { title: "The lost boarding pass", topic: "Probability", level: 3,
    prompt: "100 passengers board a plane with 100 seats. The first has lost their pass and sits in a random seat. Everyone else takes their own seat if it is free, or a random free seat if not. What is the probability the last passenger gets their own seat?",
    answer: 1 / 2, shown: "1/2",
    hint: "When the last person boards, only two seats can possibly be left.",
    why: "The last free seat is always either seat 1 or the last passenger's seat, and at every step those two are equally likely to be taken first. So it is 1/2." },
  { title: "Two reds", topic: "Probability", level: 1,
    prompt: "A bag has 3 red and 2 blue marbles. You draw 2 without putting the first back. What is the probability both are red?",
    answer: 3 / 10, shown: "3/10",
    hint: "The second draw comes from a bag with one fewer red.",
    why: "3/5 × 2/4 = 6/20 = 3/10." },
  { title: "A random walk", topic: "Markets", level: 2,
    prompt: "A $100 stock goes up 10% or down 10% each day with equal chance. What is its expected price in dollars after 2 days?",
    answer: 100, shown: "$100",
    hint: "Each day, the expected multiplier is ½ × 1.1 + ½ × 0.9.",
    why: "The expected multiplier is 1 each day, so the expected price stays $100. But the most common outcome, up then down, leaves it at $99. The average and the typical case are not the same." },
  { title: "Low roller", topic: "Expected value", level: 3,
    prompt: "You roll two dice and keep the smaller number. What is its expected value? (Give 2 decimal places.)",
    answer: 91 / 36, shown: "91/36 ≈ 2.53",
    hint: "The minimum is at least k when both dice are at least k. Then E[min] = sum over k of P(min ≥ k).",
    why: "P(min ≥ k) = ((7 − k)/6)². Adding for k = 1 to 6 gives (36 + 25 + 16 + 9 + 4 + 1)/36 = 91/36 ≈ 2.53." },
  { title: "High roller", topic: "Expected value", level: 3,
    prompt: "You roll two dice and keep the larger number. What is its expected value? (Give 2 decimal places.)",
    answer: 161 / 36, shown: "161/36 ≈ 4.47",
    hint: "The minimum plus the maximum equals the sum of both dice.",
    why: "E[max] + E[min] = E[sum] = 7. The smaller die averages 91/36, so E[max] = 7 − 91/36 = 161/36 ≈ 4.47." },
  { title: "Waiting for the bus", topic: "Expected value", level: 1,
    prompt: "A bus comes exactly every 10 minutes. You arrive at a random time. On average, how many minutes do you wait?",
    answer: 5, shown: "5 minutes",
    hint: "Your wait is equally likely to be anything from 0 to 10 minutes.",
    why: "A uniform wait from 0 to 10 averages 5 minutes." },
  { title: "Nobody's own hat", topic: "Probability", level: 3,
    prompt: "A huge number of people check their hats, and the hats are handed back at random. What is the probability that nobody gets their own hat? (Give 3 decimal places.)",
    answer: 1 / Math.E, shown: "1/e ≈ 0.368",
    hint: "Each person misses their hat with chance close to 1 − 1/n, and there are n people.",
    why: "The chance approaches 1/e ≈ 0.368 as the crowd grows. It is close to that even for 10 people. These shuffles are called derangements." },
  { title: "Poker hands", topic: "Counting", level: 2,
    prompt: "How many different 5-card hands can be dealt from a standard 52-card deck?",
    answer: 2598960, shown: "2,598,960",
    hint: "Order does not matter, so use 52 choose 5.",
    why: "52 × 51 × 50 × 49 × 48 / 5! = 2,598,960." },
  { title: "Hearts or kings", topic: "Probability", level: 1,
    prompt: "You draw one card. What is the probability it is a heart or a king?",
    answer: 4 / 13, shown: "4/13",
    hint: "Do not count the king of hearts twice.",
    why: "13 hearts + 4 kings − 1 king of hearts = 16 cards. 16/52 = 4/13." },
  { title: "Two of four", topic: "Probability", level: 1,
    prompt: "You flip a fair coin 4 times. What is the probability of exactly 2 heads?",
    answer: 3 / 8, shown: "3/8",
    hint: "Count the ways to choose which 2 flips are heads, out of 16 outcomes.",
    why: "4 choose 2 = 6 ways, out of 2⁴ = 16. 6/16 = 3/8." },
  { title: "Trailing zeros", topic: "Counting", level: 2,
    prompt: "How many zeros are at the end of 100! (100 factorial)?",
    answer: 24, shown: "24",
    hint: "Each zero comes from a 10 = 2 × 5, and there are always more 2s than 5s.",
    why: "Count the 5s: 100/5 = 20 numbers have a 5, and 100/25 = 4 have a second one. 20 + 4 = 24." },
  { title: "Sum to 100", topic: "Counting", level: 1,
    prompt: "What is 1 + 2 + 3 + … + 100?",
    answer: 5050, shown: "5,050",
    hint: "Pair the first number with the last: 1 + 100, 2 + 99, …",
    why: "There are 50 pairs that each add to 101, so 50 × 101 = 5,050." },
  { title: "Clock hands", topic: "Logic", level: 2,
    prompt: "What is the angle in degrees between the hour and minute hands at 3:15?",
    answer: 7.5, shown: "7.5°",
    hint: "The hour hand keeps moving. By 3:15 it is a quarter of the way from 3 to 4.",
    why: "The minute hand points at 3 (90°). The hour hand has moved past 3 by a quarter of 30°, so it is at 97.5°. The gap is 7.5°." },
  { title: "Fair coin from a biased one", topic: "Logic", level: 3,
    prompt: "A coin lands heads 70% of the time. To get a fair result, you flip it twice: HT means A wins, TH means B wins, and HH or TT means flip twice again. On average, how many flips does one fair result take? (Give 2 decimal places.)",
    answer: 2 / 0.42, shown: "≈ 4.76",
    hint: "Each round of 2 flips ends with probability P(HT) + P(TH).",
    why: "A round ends with probability 0.7 × 0.3 × 2 = 0.42. You need 1/0.42 rounds on average, each 2 flips: 2/0.42 ≈ 4.76 flips." },
  { title: "Expected heads squared", topic: "Expected value", level: 3,
    prompt: "You flip a fair coin 4 times and count the heads, H. What is the expected value of H²?",
    answer: 5, shown: "5",
    hint: "E[H²] = Var(H) + (E[H])². For n fair flips, E[H] = n/2 and Var(H) = n/4.",
    why: "E[H] = 2 and Var(H) = 1, so E[H²] = 1 + 4 = 5." },
  { title: "Doubling down", topic: "Markets", level: 2,
    prompt: "A portfolio loses 20% of its value. What percent gain does it need to get back to where it started?",
    answer: 25, shown: "25%", percent: true,
    hint: "Start with $100. After the loss you have $80.",
    why: "To go from $80 back to $100 you need $20 more, which is 25% of $80. Recovering always takes a bigger gain than the loss." },
  { title: "Sum of three dice", topic: "Probability", level: 2,
    prompt: "You roll three dice. What is the probability that they add up to 18?",
    answer: 1 / 216, shown: "1/216",
    hint: "Only one combination works.",
    why: "Only 6, 6, 6 makes 18, and there are 6³ = 216 outcomes. So 1/216." },
  { title: "Committee", topic: "Counting", level: 1,
    prompt: "In how many ways can you choose a 3-person team from 8 students?",
    answer: 56, shown: "56",
    hint: "Order does not matter: 8 choose 3.",
    why: "8 × 7 × 6 / (3 × 2 × 1) = 56." },
  { title: "Same color socks", topic: "Logic", level: 1,
    prompt: "A drawer has 10 black socks and 10 white socks. In the dark, how many socks must you pull out to be sure you have a matching pair?",
    answer: 3, shown: "3",
    hint: "There are only two colors.",
    why: "With 3 socks and only 2 colors, two of them must match. This is the pigeonhole principle." },
];

/** The day number in Indiana time, where day 1 is LAUNCH_DAY. */
export function dayNumber(now = new Date()): number {
  const ymd = new Intl.DateTimeFormat("en-CA", { timeZone: "America/Indiana/Indianapolis", year: "numeric", month: "2-digit", day: "2-digit" }).format(now);
  return Math.round((Date.parse(ymd) - Date.parse(LAUNCH_DAY)) / 86400000) + 1;
}

export function puzzleFor(day: number): Puzzle {
  const n = PUZZLES.length;
  return PUZZLES[(((day - 1) % n) + n) % n];
}

/** Reads "1/6", "0.167", "16.7%", "$4.25" or "2,598,960". Returns null if it is not a number. */
export function parseAnswer(raw: string, percent = false): number | null {
  let s = raw.trim().toLowerCase().replace(/[$,\s]/g, "").replace(/(dollars?|cents?|mph|minutes?|years?|°|degrees?|days?|day)/g, "");
  const pct = s.endsWith("%");
  if (pct) s = s.slice(0, -1);
  let v: number;
  const frac = s.match(/^(-?\d*\.?\d+)\/(\d*\.?\d+)$/);
  if (frac) v = Number(frac[1]) / Number(frac[2]);
  else if (/^-?\d*\.?\d+$/.test(s)) v = Number(s);
  else return null;
  if (!Number.isFinite(v)) return null;
  return pct && !percent ? v / 100 : v;
}

export function isCorrect(p: Puzzle, value: number): boolean {
  // Whole-number answers must be exact. Others allow a small rounding error.
  if (Number.isInteger(p.answer)) return Math.abs(value - p.answer) < 1e-9;
  const tol = Math.max(0.0005, Math.abs(p.answer) * 0.005);
  return Math.abs(value - p.answer) <= tol;
}
