import type { Lesson } from "./types";

export const c: Lesson[] = [
  { slug: "hello-c", title: "Hello, C", summary: "The shape of a C program, and why it cares about types.",
    steps: [
      { kind: "read", title: "Closer to the machine", body: [
        "**C** is one of the oldest languages still in everyday use. It gives you very direct control over what the computer does, which makes it fast. The trading systems quant developers build are written in C++, a language that grew out of C.",
        "Every C program has a function called `main`. The computer starts there and runs the lines between the curly braces `{ }` in order.",
        "Each instruction ends with a semicolon. `printf` prints text, and `\\n` inside the text means start a new line." ],
        example: '#include <stdio.h>\n\nint main() {\n    printf("Hi\\n");\n    return 0;\n}' },
      { kind: "code", lang: "c", title: "Say hello", body: ["The first line, `#include <stdio.h>`, brings in `printf`. `return 0;` tells the computer the program finished without a problem."],
        task: ["Print `Hello, quant` followed by a new line."],
        starter: '#include <stdio.h>\n\nint main() {\n    // Your code here\n\n    return 0;\n}\n', solution: '#include <stdio.h>\n\nint main() {\n    printf("Hello, quant\\n");\n\n    return 0;\n}\n',
        checks: [{ code: "printf\\s*\\(", msg: "Use printf( ) to print." }, { out: "^Hello, quant\\s*$", msg: "The output should be exactly: Hello, quant" }],
        hint: 'printf("Hello, quant\\n");' },
      { kind: "read", title: "Types", body: [
        "In C you must say what kind of value each variable holds. `int` is a whole number. `double` is a number with a decimal point.",
        "Knowing the type in advance lets the computer set aside exactly the right amount of memory, which is part of why C is fast.",
        "To print a number, `printf` needs a placeholder: `%d` for an int, `%f` for a double. `%.1f` shows one decimal place." ],
        example: 'int flips = 100;\ndouble price = 9.5;\nprintf("%d flips at %.2f\\n", flips, price);' },
      { kind: "code", lang: "c", title: "Expected value in C", body: ["The coin bet once more: win 12 or lose 4."],
        task: ["Declare a `double` called `ev` equal to half of `win` plus half of `lose`."],
        starter: '#include <stdio.h>\n\nint main() {\n    double win = 12.0;\n    double lose = -4.0;\n\n    // Declare ev here\n\n    printf("%.1f\\n", ev);\n    return 0;\n}\n',
        solution: '#include <stdio.h>\n\nint main() {\n    double win = 12.0;\n    double lose = -4.0;\n\n    double ev = 0.5 * win + 0.5 * lose;\n\n    printf("%.1f\\n", ev);\n    return 0;\n}\n',
        checks: [{ code: "double\\s+ev\\s*=", msg: "Declare it with its type: double ev = ...;" }, { out: "^4\\.0\\s*$", msg: "ev should print as 4.0." }],
        hint: "double ev = 0.5 * win + 0.5 * lose;" },
      { kind: "mc", q: "In C, `7` and `2` are both ints. What is `7 / 2`?", options: ["3.5", "3", "4", "An error"], answer: 1,
        explain: "Dividing two ints gives an int, and the decimal part is thrown away. To get 3.5, make one of them a double: 7.0 / 2." },
    ] },
  { slug: "loops-and-functions", title: "Loops and functions", summary: "Repeat work and package it up.",
    steps: [
      { kind: "read", title: "The for loop", body: [
        "A C `for` loop has three parts in its brackets: where to start, when to keep going, and what to change after each pass.",
        "`i++` means add 1 to `i`. `total += i` means add `i` to `total`." ],
        example: 'int total = 0;\nfor (int i = 1; i <= 3; i++) {\n    total += i;\n}\n// total is now 6' },
      { kind: "code", lang: "c", title: "Add up 1 to 100", body: ["Write the loop yourself."],
        task: ["Use a for loop to add every whole number from 1 to 100 to `total`."],
        starter: '#include <stdio.h>\n\nint main() {\n    int total = 0;\n\n    // Your loop here\n\n    printf("%d\\n", total);\n    return 0;\n}\n',
        solution: '#include <stdio.h>\n\nint main() {\n    int total = 0;\n\n    for (int i = 1; i <= 100; i++) {\n        total += i;\n    }\n\n    printf("%d\\n", total);\n    return 0;\n}\n',
        checks: [{ code: "for\\s*\\(", msg: "Use a for loop." }, { out: "^5050\\s*$", msg: "The total should be 5050. Check that the loop runs while i <= 100." }],
        hint: "for (int i = 1; i <= 100; i++) {\n    total += i;\n}" },
      { kind: "code", lang: "c", title: "A function", body: [
        "A C function states the type it gives back and the type of each input. This one takes three doubles and returns a double." ],
        task: ["Make `expected_value` return `p` times `win` plus `(1 - p)` times `lose`."],
        starter: '#include <stdio.h>\n\ndouble expected_value(double win, double lose, double p) {\n    // Replace the next line\n    return 0;\n}\n\nint main() {\n    printf("%.2f\\n", expected_value(12, -4, 0.5));\n    printf("%.2f\\n", expected_value(100, -10, 0.1));\n    return 0;\n}\n',
        solution: '#include <stdio.h>\n\ndouble expected_value(double win, double lose, double p) {\n    return p * win + (1 - p) * lose;\n}\n\nint main() {\n    printf("%.2f\\n", expected_value(12, -4, 0.5));\n    printf("%.2f\\n", expected_value(100, -10, 0.1));\n    return 0;\n}\n',
        checks: [{ out: "^4\\.00\\s*$", msg: "The coin bet should print 4.00." }, { out: "^1\\.00\\s*$", msg: "The second bet should print 1.00: 0.1 × 100 + 0.9 × (−10)." }],
        hint: "return p * win + (1 - p) * lose;" },
      { kind: "mc", q: "How many times does the body of this loop run?", code: "for (int i = 0; i < 5; i++) {\n    // body\n}", options: ["4", "5", "6", "It never stops"], answer: 1,
        explain: "i takes the values 0, 1, 2, 3 and 4. That is five passes." },
    ] },
  { slug: "arrays-and-pointers", title: "Arrays and pointers", summary: "How C stores data, and how to reach it directly.",
    steps: [
      { kind: "read", title: "Arrays", body: [
        "An **array** is a row of values of the same type, stored side by side in memory. You say how many it holds when you create it.",
        "You reach each value by its position, and positions start at 0. In an array of 8 values, the last one is at position 7." ],
        example: "int results[3] = {12, -4, 12};\n// results[0] is 12\n// results[2] is 12" },
      { kind: "code", lang: "c", title: "Average an array", body: [
        "To divide and keep the decimals, one side must be a double. Writing `(double) total` treats total as a double for that calculation." ],
        task: ["Add up the eight values in `results` with a loop.", "The two printf lines then show the total and the average."],
        starter: '#include <stdio.h>\n\nint main() {\n    int results[8] = {12, -4, -4, 12, 12, -4, 12, -4};\n    int total = 0;\n\n    // Your loop here\n\n    printf("%d\\n", total);\n    printf("%.2f\\n", (double) total / 8);\n    return 0;\n}\n',
        solution: '#include <stdio.h>\n\nint main() {\n    int results[8] = {12, -4, -4, 12, 12, -4, 12, -4};\n    int total = 0;\n\n    for (int i = 0; i < 8; i++) {\n        total += results[i];\n    }\n\n    printf("%d\\n", total);\n    printf("%.2f\\n", (double) total / 8);\n    return 0;\n}\n',
        checks: [{ code: "for\\s*\\(", msg: "Use a for loop over the positions 0 to 7." }, { out: "^32\\s*$", msg: "The total should be 32." }, { out: "^4\\.00\\s*$", msg: "The average should be 4.00." }],
        hint: "for (int i = 0; i < 8; i++) {\n    total += results[i];\n}" },
      { kind: "read", title: "Pointers", body: [
        "Every variable lives somewhere in memory, and that place has an address. A **pointer** is a variable that holds an address.",
        "`&x` means the address of x. `int *p = &x;` makes `p` point at x. Then `*p` means the value at that address, so changing `*p` changes x itself.",
        "Pointers let a program pass around the location of data instead of copying the data. That saves time, and in trading, time is money." ],
        example: "int x = 5;\nint *p = &x;\n*p = 6;\n// x is now 6" },
      { kind: "code", lang: "c", title: "Change it through a pointer", body: ["`p` already points at `x`."],
        task: ["Use `p` to change `x` to 10. Do not write `x = 10`."],
        starter: '#include <stdio.h>\n\nint main() {\n    int x = 5;\n    int *p = &x;\n\n    // Change x through p\n\n    printf("%d\\n", x);\n    return 0;\n}\n',
        solution: '#include <stdio.h>\n\nint main() {\n    int x = 5;\n    int *p = &x;\n\n    *p = 10;\n\n    printf("%d\\n", x);\n    return 0;\n}\n',
        checks: [{ code: "\\*\\s*p\\s*=\\s*10", msg: "Assign through the pointer: *p = 10;" }, { out: "^10\\s*$", msg: "x should print as 10." }],
        hint: "*p = 10;" },
      { kind: "mc", q: "What does a pointer hold?", options: ["A copy of a value", "The address where a value is stored", "The name of a variable", "The type of a variable"], answer: 1,
        explain: "A pointer stores a location in memory. Following it gets you to the value." },
      { kind: "read", title: "Why speed matters", body: [
        "When a price changes, many firms see it at almost the same moment. The first one to react gets the trade. The gap between first and second can be a few millionths of a second.",
        "That is why quant developers care about types, memory and pointers. Code that avoids wasted work is code that gets there first." ] },
    ] },
  { slug: "quiz", title: "Track quiz", summary: "Five questions. Get four right to finish the track.", quiz: true,
    steps: [
      { kind: "mc", q: "Where does a C program start running?", options: ["At the first line of the file", "In the function called main", "At the first printf", "At #include"], answer: 1, explain: "Execution always begins in main." },
      { kind: "mc", q: "Which type holds a number with a decimal point?", options: ["int", "double", "char", "void"], answer: 1, explain: "int is for whole numbers, double for decimals." },
      { kind: "mc", q: "What does this print?", code: 'int a = 9;\nint b = 2;\nprintf("%d\\n", a / b);', options: ["4.5", "4", "5", "An error"], answer: 1, explain: "Both are ints, so the decimal part is dropped." },
      { kind: "mc", q: "An array is declared as `int v[5]`. What is the position of its last value?", options: ["5", "4", "6", "1"], answer: 1, explain: "Positions start at 0, so five values sit at 0, 1, 2, 3 and 4." },
      { kind: "mc", q: "After this code, what is `x`?", code: "int x = 1;\nint *p = &x;\n*p = *p + 4;", options: ["1", "4", "5", "An address"], answer: 2, explain: "*p is x. The line reads x, adds 4, and stores 5 back in x." },
    ] },
];
