import type { Lesson } from "./types";

export const python: Lesson[] = [
  { slug: "first-lines", title: "Your first lines", summary: "Print, variables and a little arithmetic.",
    steps: [
      { kind: "read", title: "Telling a computer what to do", body: [
        "A program is a list of instructions the computer follows from top to bottom. **Python** is the language most quant research is written in, because it reads almost like English.",
        "The first instruction to learn is `print`. It shows whatever you put inside the brackets. Text goes in quotes.",
        "In these lessons the editor is on the right. **Run** shows what your code does. **Check** tells you whether it does what the step asks." ],
        example: 'print("Hello")\nprint(2 + 3)' },
      { kind: "code", lang: "python", title: "Say hello", body: ["Time to write a line yourself."], task: ['Print the text `Hello, quant`.'],
        starter: "# Write your code below\n", solution: 'print("Hello, quant")\n',
        checks: [{ code: "print\\(", msg: "Use print( ) to show text." }, { out: "^Hello, quant\\s*$", msg: "The output should be exactly: Hello, quant" }],
        hint: 'Text needs quotes: print("Hello, quant")' },
      { kind: "code", lang: "python", title: "Variables", body: [
        "A **variable** is a name for a value. You create one with `=`. After `win = 12`, writing `win` anywhere means 12.",
        "The coin bet pays 12 on heads and loses 4 on tails. Its expected value is half of each." ],
        task: ["Create a variable `ev` equal to half of `win` plus half of `lose`.", "Leave the `print(ev)` line as it is."],
        starter: "win = 12\nlose = -4\n\n# Create ev here\n\nprint(ev)\n", solution: "win = 12\nlose = -4\n\nev = 0.5 * win + 0.5 * lose\n\nprint(ev)\n",
        checks: [{ code: "ev\\s*=[^=]", msg: "Create a variable named ev with =." }, { code: "ev\\s*=.*(win.*lose|lose.*win)", msg: "Build ev from the win and lose variables instead of typing the numbers." }, { out: "^4(\\.0)?\\s*$", msg: "ev should come out as 4.0. Half of 12 plus half of -4." }],
        hint: "Use * to multiply: 0.5 * win + 0.5 * lose" },
      { kind: "mc", q: "What does this print?", code: "x = 3\nx = x + 2\nprint(x)", options: ["3", "5", "x + 2", "An error"], answer: 1,
        explain: "The second line takes the old value of x, adds 2, and stores the result back in x." },
      { kind: "code", lang: "python", title: "Text and numbers together", body: ["`print` can show several things at once. Separate them with commas and it puts a space between them."],
        task: ["Print the text `EV is` followed by the value of `ev`, using one print."],
        starter: "ev = 0.5 * 12 + 0.5 * -4\n\n", solution: 'ev = 0.5 * 12 + 0.5 * -4\n\nprint("EV is", ev)\n',
        checks: [{ code: "print\\(.*ev", msg: "Pass ev to print so the number comes from the variable." }, { out: "^EV is 4\\.0\\s*$", msg: "The output should be: EV is 4.0" }],
        hint: 'print("EV is", ev)' },
    ] },
  { slug: "decisions-and-loops", title: "Decisions and loops", summary: "Make your code choose, and make it repeat.",
    steps: [
      { kind: "read", title: "If and else", body: [
        "`if` runs a block of code only when a condition is true. `else` covers every other case.",
        "The lines inside each block are **indented** by four spaces. Python uses that indentation to know what belongs to the block, so it matters." ],
        example: 'price = 9\nif price < 10:\n    print("buy")\nelse:\n    print("wait")' },
      { kind: "code", lang: "python", title: "Play or pass", body: ["A quant's rule: take a bet when its expected value is above zero."],
        task: ['If `ev` is greater than 0, print `play`.', 'Otherwise print `pass`.'],
        starter: "ev = 0.5 * 12 + 0.5 * -4\n\n", solution: 'ev = 0.5 * 12 + 0.5 * -4\n\nif ev > 0:\n    print("play")\nelse:\n    print("pass")\n',
        checks: [{ code: "if\\s+ev\\s*>\\s*0", msg: "Start with: if ev > 0:" }, { code: "else\\s*:", msg: "Add an else: branch that prints pass." }, { out: "^play\\s*$", msg: "With this ev the output should be: play" }],
        hint: 'if ev > 0:\n    print("play")\nelse:\n    print("pass")' },
      { kind: "read", title: "For loops", body: [
        "A `for` loop repeats a block once for each item in a sequence. `range(1, 4)` produces 1, 2, 3. It stops just before the second number.",
        "`total += n` is short for `total = total + n`." ],
        example: "total = 0\nfor n in range(1, 4):\n    total += n\nprint(total)   # 6" },
      { kind: "code", lang: "python", title: "Add up 1 to 100", body: ["A loop can do in two lines what would take you a hundred."],
        task: ["Use a for loop to add every whole number from 1 to 100 to `total`."],
        starter: "total = 0\n\n# Your loop here\n\nprint(total)\n", solution: "total = 0\n\nfor n in range(1, 101):\n    total += n\n\nprint(total)\n",
        checks: [{ code: "for\\s+\\w+\\s+in\\s+", msg: "Use a for loop: for n in range(...):" }, { out: "^5050\\s*$", msg: "The total should be 5050. Remember range stops just before its second number." }],
        hint: "range(1, 101) gives 1 up to 100." },
      { kind: "code", lang: "python", title: "Average a list", body: [
        "A **list** holds many values in order, written in square brackets. A for loop can walk through a list directly, and `len(results)` tells you how many items it has." ],
        task: ["`results` holds what you won or lost on eight flips. Print the average result per flip."],
        starter: "results = [12, -4, -4, 12, 12, -4, 12, -4]\n\n", solution: "results = [12, -4, -4, 12, 12, -4, 12, -4]\n\ntotal = 0\nfor r in results:\n    total += r\n\nprint(total / len(results))\n",
        checks: [{ code: "results", msg: "Work from the results list." }, { out: "^4\\.0\\s*$", msg: "The average should be 4.0: the total divided by the number of flips." }],
        hint: "Add everything up in a loop, then divide by len(results)." },
      { kind: "mc", q: "Which numbers does `range(1, 5)` produce?", options: ["1, 2, 3, 4, 5", "1, 2, 3, 4", "0, 1, 2, 3, 4", "2, 3, 4, 5"], answer: 1,
        explain: "range starts at the first number and stops just before the second." },
    ] },
  { slug: "functions", title: "Functions", summary: "Package a calculation so you can reuse it.",
    steps: [
      { kind: "read", title: "Define once, use anywhere", body: [
        "A **function** is a named piece of code. You define it once with `def`, then call it as often as you like with different inputs.",
        "`return` hands the answer back to whoever called the function." ],
        example: "def double(x):\n    return x * 2\n\nprint(double(21))   # 42" },
      { kind: "code", lang: "python", title: "An expected value function", body: [
        "Every bet so far has had a win amount, a loss amount and a probability of winning. That makes it a good function." ],
        task: ["Make `expected_value` return `p` times `win` plus `(1 - p)` times `lose`."],
        starter: "def expected_value(win, lose, p):\n    # Replace the next line\n    pass\n\nprint(expected_value(12, -4, 0.5))\nprint(expected_value(100, -10, 0.1))\n",
        solution: "def expected_value(win, lose, p):\n    return p * win + (1 - p) * lose\n\nprint(expected_value(12, -4, 0.5))\nprint(expected_value(100, -10, 0.1))\n",
        checks: [{ code: "return", msg: "Use return to hand back the answer." }, { out: "^4\\.0\\s*$", msg: "The coin bet should give 4.0." }, { out: "^1\\.0\\s*$", msg: "The second bet should give 1.0: 0.1 × 100 + 0.9 × (−10)." }],
        hint: "return p * win + (1 - p) * lose" },
      { kind: "code", lang: "python", title: "Your own function", body: ["Now write one from scratch."],
        task: ["Define a function `average` that takes a list called `numbers` and returns its average."],
        starter: "# Define average(numbers) here\n\n\nprint(average([3, 5, 10]))\n", solution: "def average(numbers):\n    total = 0\n    for n in numbers:\n        total += n\n    return total / len(numbers)\n\nprint(average([3, 5, 10]))\n",
        checks: [{ code: "def\\s+average\\s*\\(", msg: "Start with: def average(numbers):" }, { code: "return", msg: "Use return to hand back the answer." }, { out: "^6\\.0\\s*$", msg: "average([3, 5, 10]) should be 6.0." }],
        hint: "Add up the numbers in a loop, then return the total divided by len(numbers)." },
      { kind: "mc", q: "What does this print?", code: "def add(a, b):\n    a + b\n\nprint(add(2, 3))", options: ["5", "None", "a + b", "An error"], answer: 1,
        explain: "The function works out a + b but never returns it. A function with no return gives back None." },
    ] },
  { slug: "simulate-it", title: "Simulate it", summary: "Check the math by running the experiment ten thousand times.",
    steps: [
      { kind: "read", title: "Random numbers", body: [
        "Quants do not only calculate answers. They also **simulate**: run the experiment many times in code and see what happens.",
        "The `random` module makes random numbers. `random.random()` gives a decimal between 0 and 1, different every time. It is below 0.5 half the time, which makes it a coin." ],
        example: "import random\n\nprint(random.random())" },
      { kind: "code", lang: "python", title: "One flip", body: ["Turn a random number into one flip of the coin bet."],
        task: ["Set `result` to 12 if `random.random()` is below 0.5, and to -4 otherwise."],
        starter: "import random\n\n# Set result here\n\nprint(result)\n", solution: "import random\n\nif random.random() < 0.5:\n    result = 12\nelse:\n    result = -4\n\nprint(result)\n",
        checks: [{ code: "random\\.random\\(\\)", msg: "Use random.random() to flip the coin." }, { out: "^(12|-4)\\s*$", msg: "The output should be either 12 or -4." }],
        hint: "if random.random() < 0.5:\n    result = 12\nelse:\n    result = -4" },
      { kind: "code", lang: "python", title: "Ten thousand flips", body: [
        "One flip tells you nothing. Ten thousand tell you the expected value." ],
        task: ["Repeat the flip `flips` times, adding 12 or -4 to `total` each time.", "The last line prints the average. It should land close to 4."],
        starter: "import random\n\nflips = 10000\ntotal = 0\n\n# Your loop here\n\nprint(total / flips)\n",
        solution: "import random\n\nflips = 10000\ntotal = 0\n\nfor i in range(flips):\n    if random.random() < 0.5:\n        total += 12\n    else:\n        total -= 4\n\nprint(total / flips)\n",
        checks: [{ code: "for\\s+\\w+\\s+in\\s+range", msg: "Use a for loop over range(flips)." }, { code: "random\\.random\\(\\)", msg: "Flip the coin with random.random() inside the loop." }, { num: [3.5, 4.5], msg: "The average should be close to 4. Check that heads adds 12 and tails subtracts 4." }],
        hint: "for i in range(flips):\n    if random.random() < 0.5:\n        total += 12\n    else:\n        total -= 4" },
      { kind: "mc", q: "You run the simulation with 100 flips, then with 1,000,000. Which average is likely to be closer to 4?", options: ["100 flips", "1,000,000 flips", "They will be equally close"], answer: 1,
        explain: "The more tries, the closer the average gets to the expected value. This is the law of large numbers, and it is why quants trust EV." },
    ] },
  { slug: "quiz", title: "Track quiz", summary: "Five questions. Get four right to finish the track.", quiz: true,
    steps: [
      { kind: "mc", q: "What does this print?", code: "a = 10\nb = 4\nprint(a - b * 2)", options: ["12", "2", "8", "16"], answer: 1, explain: "Multiplication happens first: 4 × 2 = 8, then 10 − 8 = 2." },
      { kind: "mc", q: "What does this print?", code: 'ev = -1\nif ev > 0:\n    print("play")\nelse:\n    print("pass")', options: ["play", "pass", "Nothing", "An error"], answer: 1, explain: "−1 is not greater than 0, so the else branch runs." },
      { kind: "mc", q: "What does this print?", code: "total = 0\nfor n in range(1, 4):\n    total += n\nprint(total)", options: ["3", "6", "10", "4"], answer: 1, explain: "range(1, 4) gives 1, 2, 3, and 1 + 2 + 3 = 6." },
      { kind: "mc", q: "What does `len([5, 8, 13])` give?", options: ["26", "13", "3", "5"], answer: 2, explain: "len counts the items in a list. There are three." },
      { kind: "mc", q: "What does `return` do in a function?", options: ["Prints a value on the screen", "Hands a value back to the code that called the function", "Starts the function again", "Deletes the function"], answer: 1,
        explain: "return passes the result back. print only shows something on the screen." },
    ] },
];
